version: '3.3'
networks:
  api:
    driver: 'bridge'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: api-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - api
